name: Node.js CI

on:
    push:
        branches: [main, FY-64/feature-react-hooks-구현]
    pull_request:
        branches: [main, FY-64/feature-react-hooks-구현]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x, 18.x, 20.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm i
            - name: Run build
              run: npm run build
            - name: Check for build success
              run: |
                  if [ $? -ne 0 ]; then
                    echo "Build failed with error code $?"
                    exit 1
                  fi
